<?php

namespace App\Services\Ai;

use App\Models\AiGenerationJob;
use App\Models\AiProvider;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use Throwable;

class AiGenerationService
{
    /**
     * @param array<string, mixed> $input
     * @return array<string, mixed>
     */
    public function testProvider(AiProvider $provider, array $input = []): array
    {
        if ($provider->status !== 'enabled' || empty($provider->api_key_encrypted)) {
            $result = [
                'status' => 'mock',
                'message' => 'AI provider is disabled or missing credentials; no external call was made.',
                'sample' => 'Placeholder newsletter subject generated by Core skeleton.',
            ];

            $this->record($provider, $result);

            return $result;
        }

        $baseUrl = rtrim((string) ($provider->base_url ?: 'https://api.openai.com/v1'), '/');
        $model = $provider->default_model ?: 'gpt-4.1-mini';
        try {
            $response = Http::timeout(20)
                ->withToken((string) $provider->api_key_encrypted)
                ->post($baseUrl.'/chat/completions', [
                    'model' => $model,
                    'messages' => [
                        ['role' => 'system', 'content' => 'Return a short safe newsletter test sentence.'],
                        ['role' => 'user', 'content' => $input['prompt'] ?? 'Generate a short newsletter subject test.'],
                    ],
                    'temperature' => $provider->default_temperature ?? 0.2,
                    'max_tokens' => $provider->default_max_tokens ?? 80,
                ]);
        } catch (Throwable $exception) {
            $result = [
                'status' => 'failed',
                'reason' => 'provider_request_failed',
                'message' => str($exception->getMessage())->limit(180)->toString(),
                'model' => $model,
            ];

            $this->record($provider, $result);

            return $result;
        }

        $result = [
            'status' => $response->successful() ? 'ok' : 'failed',
            'http_status' => $response->status(),
            'model' => $model,
            'usage' => $response->json('usage'),
        ];

        $this->record($provider, $result);

        return $result;
    }

    /**
     * @param array<string, mixed> $input
     */
    public function createPlaceholderJob(string $purpose, array $input, ?AiProvider $provider = null, ?int $relatedId = null, ?string $relatedType = null): AiGenerationJob
    {
        return AiGenerationJob::query()->create([
            'uuid' => (string) Str::uuid(),
            'ai_provider_id' => $provider?->id,
            'related_type' => $relatedType,
            'related_id' => $relatedId,
            'purpose' => $purpose,
            'status' => 'completed',
            'input_json' => $input,
            'output_json' => [
                'status' => 'mock',
                'message' => 'Placeholder AI draft; no provider call was made.',
            ],
            'completed_at' => now(),
        ]);
    }

    /**
     * @param array<string, mixed> $result
     */
    private function record(AiProvider $provider, array $result): void
    {
        $provider->update([
            'last_test_result_json' => $result,
            'last_tested_at' => now(),
        ]);
    }
}
