<?php

return [
    'admin_path' => env('CORE_ADMIN_PATH', 'core-admin'),

    'allowed_origins' => array_values(array_filter(array_map(
        'trim',
        explode(',', env('CORE_ALLOWED_ORIGINS', 'https://www.clubalfa.it,https://www.motorisumotori.it')),
    ))),

    'sites' => [
        'clubalfa_it' => [
            'origin' => 'https://www.clubalfa.it',
            'language' => 'it',
            'push_group' => 'clubalfa_it',
            'manifest_id' => '/pwa/clubalfa-it',
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
        ],
        'clubalfa_en' => [
            'origin' => 'https://www.clubalfa.it',
            'language' => 'en',
            'push_group' => 'clubalfa_en',
            'manifest_id' => '/pwa/clubalfa-en',
            'service_worker_url' => '/en/smart_sw.js',
            'service_worker_scope' => '/en/',
        ],
        'motorisumotori_it' => [
            'origin' => 'https://www.motorisumotori.it',
            'language' => 'it',
            'push_group' => 'motorisumotori_it',
            'manifest_id' => null,
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
        ],
    ],

    'legacy_push' => [
        'connection' => env('LEGACY_PUSH_DB_CONNECTION_NAME', 'legacy_push'),
        'allowed_platforms' => [
            5 => 'Chrome',
            7 => 'Firefox',
            9 => 'Opera',
            10 => 'Samsung Browser',
            11 => 'Edge',
        ],
        'app_mappings' => [
            1 => [
                'site_code' => 'clubalfa_it',
                'name' => 'ClubAlfa.it',
                'origin' => 'https://www.clubalfa.it',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'clubalfa_it',
                'merge_group' => 'clubalfa_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            11 => [
                'site_code' => 'clubalfa_it',
                'name' => 'ClubAlfa.it Automobili',
                'origin' => 'https://www.clubalfa.it',
                'path_prefix' => '/automobili/',
                'language' => 'it',
                'section' => 'automobili',
                'push_group' => 'clubalfa_it',
                'merge_group' => 'clubalfa_it',
                'service_worker_url' => '/automobili/smart_sw.js',
                'service_worker_scope' => '/automobili/',
            ],
            12 => [
                'site_code' => 'clubalfa_en',
                'name' => 'ClubAlfa.it English',
                'origin' => 'https://www.clubalfa.it',
                'path_prefix' => '/en/',
                'language' => 'en',
                'section' => 'en',
                'push_group' => 'clubalfa_en',
                'merge_group' => 'clubalfa_en',
                'service_worker_url' => '/en/smart_sw.js',
                'service_worker_scope' => '/en/',
            ],
            10 => [
                'site_code' => 'motorisumotori_it',
                'name' => 'Motorisumotori.it',
                'origin' => 'https://www.motorisumotori.it',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'motorisumotori_it',
                'merge_group' => 'motorisumotori_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            2 => [
                'site_code' => 'mbenz_it',
                'name' => 'Mbenz.it',
                'origin' => 'https://mbenz.it',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'mbenz_it',
                'merge_group' => 'mbenz_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            6 => [
                'site_code' => 'alfavirtualclub_it',
                'name' => 'AlfaVirtualClub.it',
                'origin' => 'https://alfavirtualclub.it',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'alfavirtualclub_it',
                'merge_group' => 'alfavirtualclub_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            7 => [
                'site_code' => 'notizieauto_it',
                'name' => 'NotizieAuto.it',
                'origin' => null,
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'notizieauto_it',
                'merge_group' => 'notizieauto_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            13 => [
                'site_code' => 'robotica_news',
                'name' => 'Robotica.news',
                'origin' => 'https://robotica.news',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'robotica_news',
                'merge_group' => 'robotica_news',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
        ],
    ],
];
