<?php

return [
    'admin_path' => env('CORE_ADMIN_PATH', 'core-admin'),

    'allowed_origins' => array_values(array_filter(array_map(
        'trim',
        explode(',', env('CORE_ALLOWED_ORIGINS', 'https://www.clubalfa.it,https://www.motorisumotori.it')),
    ))),

    'bridge' => [
        'api_base' => env('CORE_BRIDGE_API_BASE', env('APP_URL', 'https://core.staratlasmedia.com')),
        'sdk_url' => env('CORE_SDK_URL', 'https://core.staratlasmedia.com/sdk/core-sdk.iife.js'),
        'setup_token_ttl_minutes' => (int) env('CORE_BRIDGE_SETUP_TOKEN_TTL_MINUTES', 60),
        'hmac_timestamp_tolerance_seconds' => (int) env('CORE_BRIDGE_HMAC_TOLERANCE_SECONDS', 300),
        'plugin_package_code' => env('CORE_BRIDGE_PLUGIN_PACKAGE_CODE', 'star-atlas-core-bridge'),
        'default_update_channel' => env('CORE_BRIDGE_PLUGIN_UPDATE_CHANNEL', 'stable'),
        'plugin_download_ttl_minutes' => (int) env('CORE_BRIDGE_PLUGIN_DOWNLOAD_TTL_MINUTES', 30),
    ],

    'sites' => [
        'clubalfa_it' => [
            'origin' => 'https://www.clubalfa.it',
            'language' => 'it',
            'push_group' => 'clubalfa_it',
            'manifest_id' => '/pwa/clubalfa-it',
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
        ],
        'clubalfa_en' => [
            'origin' => 'https://www.clubalfa.it',
            'language' => 'en',
            'push_group' => 'clubalfa_en',
            'manifest_id' => '/pwa/clubalfa-en',
            'service_worker_url' => '/en/smart_sw.js',
            'service_worker_scope' => '/en/',
        ],
        'motorisumotori_it' => [
            'origin' => 'https://www.motorisumotori.it',
            'language' => 'it',
            'push_group' => 'motorisumotori_it',
            'manifest_id' => null,
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
        ],
    ],

    'push_groups' => [
        'clubalfa_it' => [
            'name' => 'ClubAlfa.it',
            'language' => 'it',
            'manifest_id' => '/pwa/clubalfa-it',
            'manifest_name' => 'ClubAlfa.it',
            'manifest_short_name' => 'ClubAlfa',
            'manifest_scope' => '/',
            'manifest_start_url' => '/pwa-start/?app=clubalfa_it',
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
            'sw_version' => 'core-clean-v1',
            'pwa_config_json' => [
                'description' => 'Notizie auto, Alfa Romeo, Stellantis e motori.',
                'categories' => ['news', 'automotive'],
                'background_color' => '#eceff1',
                'theme_color' => '#d12711',
                'display' => 'standalone',
                'lang' => 'it-IT',
                'dir' => 'ltr',
                'icons' => [
                    ['src' => '/android-chrome-192x192.png', 'sizes' => '192x192', 'type' => 'image/png', 'purpose' => 'any'],
                    ['src' => '/clubalfa-pwa-logo-192-msk.png', 'sizes' => '192x192', 'type' => 'image/png', 'purpose' => 'maskable'],
                    ['src' => '/android-chrome-512x512.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'any'],
                    ['src' => '/clubalfa-pwa-logo-512-msk.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'maskable'],
                ],
            ],
        ],
        'clubalfa_en' => [
            'name' => 'ClubAlfa - Global',
            'language' => 'en',
            'manifest_id' => '/pwa/clubalfa-en',
            'manifest_name' => 'ClubAlfa - Global',
            'manifest_short_name' => 'ClubAlfa',
            'manifest_scope' => '/en/',
            'manifest_start_url' => '/en/pwa-start/?app=clubalfa_en',
            'service_worker_url' => '/en/smart_sw.js',
            'service_worker_scope' => '/en/',
            'sw_version' => 'core-clean-v1',
            'pwa_config_json' => [
                'description' => 'Automotive news in English.',
                'categories' => ['news', 'automotive'],
                'background_color' => '#eceff1',
                'theme_color' => '#d12711',
                'display' => 'standalone',
                'orientation' => 'portrait',
                'lang' => 'en',
                'dir' => 'ltr',
                'icons' => [
                    ['src' => '/android-chrome-192x192.png', 'sizes' => '192x192', 'type' => 'image/png', 'purpose' => 'any'],
                    ['src' => '/clubalfa-pwa-logo-192-msk.png', 'sizes' => '192x192', 'type' => 'image/png', 'purpose' => 'maskable'],
                    ['src' => '/android-chrome-512x512.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'any'],
                    ['src' => '/clubalfa-pwa-logo-512-msk.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'maskable'],
                ],
            ],
        ],
        'motorisumotori_it' => [
            'name' => 'Motorisumotori.it',
            'language' => 'it',
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
            'sw_version' => 'core-clean-v1',
        ],
        'mbenz_it' => [
            'name' => 'Mbenz.it',
            'language' => 'it',
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
            'sw_version' => 'core-clean-v1',
        ],
        'notizieauto_it' => [
            'name' => 'NotizieAuto.it',
            'language' => 'it',
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
            'sw_version' => 'core-clean-v1',
        ],
        'alfavirtualclub_it' => [
            'name' => 'AlfaVirtualClub.it',
            'language' => 'it',
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
            'sw_version' => 'core-clean-v1',
        ],
        'robotica_news' => [
            'name' => 'Robotica.news',
            'language' => 'it',
            'service_worker_url' => '/smart_sw.js',
            'service_worker_scope' => '/',
            'sw_version' => 'core-clean-v1',
        ],
    ],

    'web_push' => [
        'vapid_subject' => env('WEB_PUSH_VAPID_SUBJECT', env('APP_URL', 'https://core.staratlasmedia.com')),
        'ttl' => (int) env('WEB_PUSH_TTL', 3600),
        'urgency' => env('WEB_PUSH_URGENCY', 'normal'),
        'batch_size' => (int) env('WEB_PUSH_BATCH_SIZE', 200),
        'timeout' => (int) env('WEB_PUSH_TIMEOUT', 30),
    ],

    'legacy_push' => [
        'connection' => env('LEGACY_PUSH_DB_CONNECTION_NAME', 'legacy_push'),
        'allowed_platforms' => [
            5 => 'Chrome',
            7 => 'Firefox',
            9 => 'Opera',
            10 => 'Samsung Browser',
            11 => 'Edge',
        ],
        'app_mappings' => [
            1 => [
                'site_code' => 'clubalfa_it',
                'name' => 'ClubAlfa.it',
                'origin' => 'https://www.clubalfa.it',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'clubalfa_it',
                'merge_group' => 'clubalfa_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            11 => [
                'site_code' => 'clubalfa_it',
                'name' => 'ClubAlfa.it Automobili',
                'origin' => 'https://www.clubalfa.it',
                'path_prefix' => '/automobili/',
                'language' => 'it',
                'section' => 'automobili',
                'push_group' => 'clubalfa_it',
                'merge_group' => 'clubalfa_it',
                'service_worker_url' => '/automobili/smart_sw.js',
                'service_worker_scope' => '/automobili/',
            ],
            12 => [
                'site_code' => 'clubalfa_en',
                'name' => 'ClubAlfa.it English',
                'origin' => 'https://www.clubalfa.it',
                'path_prefix' => '/en/',
                'language' => 'en',
                'section' => 'en',
                'push_group' => 'clubalfa_en',
                'merge_group' => 'clubalfa_en',
                'service_worker_url' => '/en/smart_sw.js',
                'service_worker_scope' => '/en/',
            ],
            10 => [
                'site_code' => 'motorisumotori_it',
                'name' => 'Motorisumotori.it',
                'origin' => 'https://www.motorisumotori.it',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'motorisumotori_it',
                'merge_group' => 'motorisumotori_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            2 => [
                'site_code' => 'mbenz_it',
                'name' => 'Mbenz.it',
                'origin' => 'https://mbenz.it',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'mbenz_it',
                'merge_group' => 'mbenz_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            6 => [
                'site_code' => 'alfavirtualclub_it',
                'name' => 'AlfaVirtualClub.it',
                'origin' => 'https://alfavirtualclub.it',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'alfavirtualclub_it',
                'merge_group' => 'alfavirtualclub_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            7 => [
                'site_code' => 'notizieauto_it',
                'name' => 'NotizieAuto.it',
                'origin' => null,
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'notizieauto_it',
                'merge_group' => 'notizieauto_it',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
            13 => [
                'site_code' => 'robotica_news',
                'name' => 'Robotica.news',
                'origin' => 'https://robotica.news',
                'path_prefix' => '/',
                'language' => 'it',
                'section' => 'main',
                'push_group' => 'robotica_news',
                'merge_group' => 'robotica_news',
                'service_worker_url' => '/smart_sw.js',
                'service_worker_scope' => '/',
            ],
        ],
    ],
];
